<?php require_once('header.php'); ?>


<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="./assets/img/deneme.png" usemap="#image-map">

<map name="image-map">
    <area target="_blank" alt="kk" title="kk" href="https://mecmot.com" coords="174,4,114,165" shape="rect" id="1">
    <area target="_blank" alt="phs" title="phs" href="https://mecmot.com" coords="250,64,197,180" shape="rect">
</map>


<script>
    let parca = document.getElementById('1')

    parca.addEventListener('mouseover',function(){
        parca.style.opacity = '0'
    })
</script>

<?php require_once('footer.php'); ?>